### ISSUE TITLE
Timeout after xx amount?

### ISSUE THREAD

**Issue by viper83** [tsundokul/ug-pro-gpx-save#1]
Hey,

After downloading a few in a row, its not working anymore and only a 'download' file can be downloaded.

Any idea?

Thanks so far!

**Comment by tsundokul** [comment]
Thanks, it looks like there's a bug when opening multiple tabs in a row, I'll look into that

**Comment by viper83** [comment]
I actually think its on UG's side. After a couple, the Officials keeps loading, and hence your tool is not able to download it.

**Comment by viper83** [comment]
Thanks for the update!

**Comment by zanzo420** [comment]
where is this 'WITCH TO THE OLD PLAYER' at?

**Comment by tsundokul** [comment]
@zanzo420 
![image](https://user-images.githubusercontent.com/42388638/184141906-285d395f-bbbf-4772-bcd5-7cb868d15a14.png)
