### ISSUE TITLE
Old player disabled

### ISSUE THREAD

**Issue by viper83** [tsundokul/ug-pro-gpx-save#3]
Hey,

seems like the old player is disabled. So we can not use this tool anymore. 
Just happened September 1st. 
Probably nothing you can do, but would be great if you can check it out!
Thanks!

**Comment by tsundokul** [comment]
I'll take a look :D thanks for letting me know

**Comment by andreasbollden** [comment]
That was quick viper83! I was just about to write the same ;)
It was fun while it lasted :)
Thank you tsundokul <3
